spring:
  application:
    name: demo

  rabbitmq:
    host: 192.168.0.184
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        acknowledge-mode: manual
    ssl:
      enables: false
      trust-store-type: PKCS12
      trust-store: rabbitmq.truststore
      trust-store-password: !
      protocol: TLSv1.2




queueconfig:
  queueName: testQ
  exchangeName: myExchange
  routingKey : myRoutingKey

s3config:
  s3url : http://192.168.0.184:9000
  region : us-west-2
  accesskeyid : "PQZEgUSS3wMMtSubdBo6"
  secretaccesskey : "B8OXpqAo3g31KY3XcTQBk3R6oap2lUTbCh5jFzMK"