spring:
  application:
    name: demo

  rabbitmq:
    host: liam.dk
    port: 5772
    username: guest
    password: S0l0ve#
    virtual-host: /
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        acknowledge-mode: manual
    ssl:
      enabled: true
      key-store :
      key-store-password :
      trust-store :
      trust-store-password :


queueconfig:
  queueName: testQ
  exchangeName: myExchange
  routingKey : myRoutingKey

s3config:
  s3url : http://liam.dk:9100
  region : us-west-2
  accesskeyid : "BONUWre9QgtymZ1Z1EAb"
  secretaccesskey : "B66PAsq2wO3tvTjo1EMZrvESackgg6sUZucNdstb"