spring:
  application:
    name: demo

  rabbitmq:
    host: 192.168.0.184
    port: 5671
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        acknowledge-mode: manual
    ssl:
      enables: true
      key-store: ssl/rabbitmq.jks
      key-store-password: S0r0ver!
      trust-store-type: PKCS12
      trust-store: ssl/cacerts
      trust-store-password: changeit
      protocol: TLSv1.3




queueconfig:
  queueName: testQ
  exchangeName: myExchange
  routingKey : myRoutingKey

s3config:
  s3url : http://liam.dk:9100
  region : us-west-2
  accesskeyid : "BONUWre9QgtymZ1Z1EAb"
  secretaccesskey : "B66PAsq2wO3tvTjo1EMZrvESackgg6sUZucNdstb"