spring:
  application:
    name: demo

  rabbitmq:
    host: 192.168.0.147
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        acknowledge-mode: manual

queueconfig:
  queueName: testQ
  exchangeName: myExchange
  routingKey : myRoutingKey

s3config:
  s3url : http://192.168.0.147:9000
  region : us-west-2
  accesskeyid : "BONUWre9QgtymZ1Z1EAb"
  secretaccesskey : "B66PAsq2wO3tvTjo1EMZrvESackgg6sUZucNdstb"